# Generated by Django 6.0.4 on 2026-06-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailhistory',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
