# Generated by Django 6.0.4 on 2026-06-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox_app', '0002_emailhistory_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailhistory',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
